### PR TITLE
Updated Lisense... sorry I couldn't help more.

### PR DESCRIPTION
**Pull request by hg0428**
I was going to add another theme too, but then I noticed that my theme's json looked different from the other themes on there, so I was probably doing something different than you even though we were both using monaco.
So, I just ended up changing the one character and updating the License. I would have done more, but I'm not too good at swift. If it was made in Python, JS, C++, or something I knew better, I would definately have helped out as much as I could.

### CODE REVIEW

**Comment by hg0428** [comment]
I only made one tiny edit, so you can merge it, or you could just choose to change the 2021 to a 2022 yourself, or not change it at all, whatever you want to do.

**Comment by bummoblizard** [comment]
Really appreciate it for contributing! However the copyright year on the license is probably not meant to change, according to this: https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

For your custom theme, it might be different because Code app uses textmate for syntax definition unlike the original Monaco. It should be the same format as the desktop VS Code.

**Comment by hg0428** [comment]
Oh, I never knew copyrights worked like that.
Well, sorry I was unable to help out.

**Comment by hg0428** [comment]
> Really appreciate it for contributing! However the copyright year on the license is probably not meant to change, according to this: https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated
> 
> For your custom theme, it might be different because Code app uses textmate for syntax definition unlike the original Monaco. It should be the same format as the desktop VS Code.

Oh, I never knew copyrights worked like that.
Sorry I was unable to help out

**Pull request closed without merging**
