### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Jeverett3000**

### CODE REVIEW

**Comment by Lukas-Batema** [comment]
Isn't there already a `README.md`?

**Comment by bummoblizard** [comment]
> Isn't there already a `README.md`?

It's for the website branch. But I'm not sure whether we want a readme there.

**Review by Lukas-Batema — CHANGES_REQUESTED** [review]
Network went out

**Review by Lukas-Batema — CHANGES_REQUESTED** [review]
Network went out...

**Review by Lukas-Batema — CHANGES_REQUESTED** [review]
This repo already has a `README.md`:
image

**Comment by Lukas-Batema** [comment]
Oops my network went out lol

**Comment by Lukas-Batema** [comment]
@bummoblizard, I think this PR is not gonna be added, since it has not been commented on, or merged since December 2, 2021. Are you still thinking about adding this, or are you gonna close it? Thanks!

**Pull request closed without merging**
