### PR TITLE
Added instructions to clone a new repo and "working directory" header in section

### PR DESCRIPTION
**Pull request by benwu030**
Screenshot 2022-12-23 at 2 54 13 PM
Screenshot 2022-12-23 at 2 54 25 PM

### CODE REVIEW

**Comment by benwu030** [comment]
Will add localised string later if this is ok

**Comment by bummoblizard** [comment]
What does FUZZ.txt mean?

**Comment by bummoblizard** [comment]
Linting is broken. Forget it for now.

**Comment by benwu030** [comment]
FUZZ.txt is the directory name. It is just a random repo i cloned from github

**Comment by bummoblizard** [comment]
> FUZZ.txt is the directory name. It is just a random repo i cloned from github

I see…. That’s a confusing name.

**Comment by bummoblizard** [comment]
I think there should be instruction on on how to select another directory. Or even make it a button, popping up the folder selection menu.

**Pull request closed without merging**
